# Python Basic

The following topics are discussed with samples in this section.
1. Numpy
   * basic
   * shape, copies
2. Pandas
3. Plot (matplotlib)

In [33]:
import numpy as np
%precision 2

'%.2f'

## Numpy

### Basic

Main object of numpy is multidimensional array (ndarray) with features of axes(dimensions) and rank(axes). Following attributes:

* **ndarray.ndim**: number of axes
* **ndarray.shape**: dimensions
* **ndarray.size**: number of the element in an array
* **ndarray.dtype**: data type of the elements array
* **ndarray.itemsize**: bytes of each element 
* **ndarray.data**: buffer

**Creation** 

In [17]:
## Creation with array 
a = np.array([[1,2,3],[4,5,6]], dtype = int)
## Creation with zeros
b = np.zeros((2,3,4),dtype=np.int16)
## Creation with empty
c = np.empty((2,3))
## Creation with arange
d = np.arange(0,2,0.3) # step size
e = np.linspace(0,2,9) # number wanted

** Operations **

Arithmetic operations are applied elementwise.


In [35]:
a = np.arange(24).reshape(2,3,4)
print(a)
# dimensional calculation
a.sum(axis=0)  #first dimension
# universal function (ufunc)
np.exp(a)
np.sqrt(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0.  ,  1.  ,  1.41,  1.73],
        [ 2.  ,  2.24,  2.45,  2.65],
        [ 2.83,  3.  ,  3.16,  3.32]],

       [[ 3.46,  3.61,  3.74,  3.87],
        [ 4.  ,  4.12,  4.24,  4.36],
        [ 4.47,  4.58,  4.69,  4.8 ]]])

** Indexcing, Slicing and interating **

In [38]:
#One dimensional case
a = np.arange(10)**3
print(a)
# step:
print(a[::-1])

[  0   1   8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]


In [45]:
# Multi-dimensional case
def f(x,y):
    return 2*x+y
b = np.fromfunction(f,(5,4),dtype=int) # generate a grid
print(b)
print(b[2,3]) # each number for a rank (5,4 in this case)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]]


7

In [ ]:
### 